Package:
 name: exogam
 type: detector
 groups: ganil germanium
 url: https://gitlab.in2p3.fr/valerian.girard-alcindor/exogam
 version: 0.1
 author: Valerian Girard-Alcindor
 mail: girard-alcindor@ijclab.in2p3.fr
 description: exogam 
 dependencies: root

Plugin: 
  token: exogam
  library: NPExogam
 
PluginCitation:
 type: Detector
 citation: 
 url: 

PluginCitation:
 type: Analysis
 citation: something else
 url: www.another-link.org

