Package:
 name: zdd
 type: detector
 groups: recoil detection
 url: https://gitlab.in2p3.fr/valerian.girard-alcindor/zdd
 version: 0.1
 author: Valerian Girard-Alcindor
 mail: girard-alcindor@ijclab.in2p3.fr
 description: zdd 
 dependencies: root

Plugin: 
  token: zdd
  library: NPZdd
 
PluginCitation:
 type: Detector
 citation: 
 url: 

PluginCitation:
 type: Analysis
 citation: something else
 url: www.another-link.org

